name: Build Non-Release Branch

on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - bugfix/*

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - run: $env.token
      - run: $env.projecttoken
      - run: Invoke-WebRequest -URI "http://localhost:8080/job/PepperDash%20Core%20Branch%20Builds/build?token=$($env.projecttoken)" -Headers @{Authorization = "Basic $([System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("ndorin:$($env.token)")))"} -Method POST -UseBasicParsing
        env:
          token: ${{ secrets.TOKEN }}
          projecttoken: ${{ secrets.PROJECTTOKEN }}
