name: Build Branch

on:
  push:
    branches:
      - feature/*
      - bugfix/*

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: Invoke-WebRequest -URI "http://localhost:8080/job/PepperDash%20Core%20Branch%20Builds/build" -credentials "ndorin:${{ secrets.TOKEN }}" -method POST
