name: Build Non-Release Branch

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - run: $Env
      - run: Invoke-WebRequest -URI "http://localhost:8080/job/PepperDash%20Core%20Branch%20Builds/build?token=$($Env.projectToken)" -Headers @{Authorization = "Basic $([System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("ndorin:$($Env.token)")))"} -Method POST -UseBasicParsing
        env:
          token: ${{ secrets.TOKEN }}
          projectToken: ${{ secrets.PROJECTTOKEN}}
